### ISSUE TITLE
Feature for allowing users to follow other users.

### ISSUE THREAD

**Issue by Ming424** [Ming424/soen341_project#11]
User Story:
As a user, I want to be able to follow other people that I am interested to so I can see their post onto a specific web page.

**Comment by jeffrey-w** [comment]
ID | Category | Subcategory | Test | Preconditions | Input | Output | Postconditions
-- | -- | -- | -- | -- | -- | -- | --
6.2.1 | Profile Page | User Info | Follow | User is logged in and on the profile page   of another user | Click on the follow button | The counter above the button is   incremented, and the button now says 'Unfollow' | The user is registered as followig the   other user
-- | -- | -- | -- | -- | -- | -- | --
6.2.2 | Profile Page | User Info | Unfollow | User is   logged in and on the profile page of another user that they follow | Click on the   unfollow button | The counter   above the button is decremented, and the button now says "Follow" | The user is   unregistered from following the other user
