### ISSUE TITLE
Create a LEAVE A COMMENT box component for leaving comments on posts

### ISSUE THREAD

**Issue by DavidLiang01** [Ming424/soen341_project#15]
Below every picture displayed on the feed, there is a box that displays the message “Leave a comment”. If the user clicks on this box, they will be prompted to type a message. The user can then click the “Comment” button to add their message to the list of comments or the “Cancel” button to stop writing a message. Once a comment is left on a post, it will appear below the picture and will be viewable by everyone who looks at that picture. #14

**Comment by DavidLiang01** [comment]
#14

**Comment by jeffrey-w** [comment]
ID | Category | Subcategory | Test | Preconditions | Input | Output | Postconditions
-- | -- | -- | -- | -- | -- | -- | --
3.2.5 | Dashboard | Comment | Comment   Button | User is   logged in and on the dashboard page     At least one photo has been posted | Click on the   comment button beneath a posted photo | A text field   and submit button appear in the panel to the right of the post | No change to   the session will be made
-- | -- | -- | -- | -- | -- | -- | --
5.1.1 | Comment   Pannel | Post Comment | Arbitrary   Text | User is   logged in and on the dashboard page     At least one photo has been posted and the user has clicked its comment   button | Enter any   string of text in the field in the panel to the right of the post; press   'Send' | The entered   comment will be displayed above the text field | The comment   will be saved
