### ISSUE TITLE
Extra feature 1: Dark mode 

### ISSUE THREAD

**Issue by DavidLiang01** [Ming424/soen341_project#65]
As a logged in user, I want to be able to change the color of the application (background color) into a black color, so that users can personalize their theme.

**Comment by Mounceph99** [comment]
As of now, dark mode works, but it is very limited. When dark mode is active, when the user changes webpage, it returns to the original color theme. #67

**Comment by Ming424** [comment]
Improved dark mode experience inwhich added a global toogle for the dark mode to avoid reset toogle on refresh.

**Comment by jeffrey-w** [comment]
ID | Category | Subcategory | Test | Preconditions | Input | Output | Postconditions
-- | -- | -- | -- | -- | -- | -- | --
3.1.3 | Dashboard | Navigation Bar | Dark Mode Enable | User is logged in and on the dashboard page | Click on the dark mode link | The colors and feel of the dashboard page   will darken | The user's preference for the dark theme   will be registered
-- | -- | -- | -- | -- | -- | -- | --
3.1.4 | Dashboard | Navigation   Bar | Dark Mode   Disable | User is   logged in and on the dashboard page     Dark mode is enabled | Click on the   dark mode link | The colors   and feel of the dashboard page will lighten | The user's   preference for the light theme will be registered
