### ISSUE TITLE
Extra Feature 2: Like Posts

### ISSUE THREAD

**Issue by DavidLiang01** [Ming424/soen341_project#68]
As a logged in user, I want to like a post that someone posted, so that the person who shared the post can see how many people liked his post.

**Comment by jeffrey-w** [comment]
ID | Category | Subcategory | Test | Preconditions | Input | Output | Postconditions
-- | -- | -- | -- | -- | -- | -- | --
3.2.3 | Dashboard | Photo Feed | Like Button | User is   logged in and on the dashboard page     At least one photo that has not been liked has been posted | Click on the   like button beneath a posted photo | The like   button will become red, and the counter next to it will increment | The like   count of the post will increase
-- | -- | -- | -- | -- | -- | -- | --
3.2.4 | Dashboard | Photo Feed | Like Button (already-liked post) | User is logged in and on the dashboard   page     At least one photo that has already been liked by the user has been posted | Click on the like button beneath a posted   photo | No output/effect | No change to the session will be made
