### ISSUE TITLE
Feature for allowing users to upload picture 

### ISSUE THREAD

**Issue by DavidLiang01** [Ming424/soen341_project#8]
User Story:
As a logged in user, I want to be able to upload a picture on my personal account, so that other users can see it.

**Comment by jeffrey-w** [comment]
ID | Category | Subcategory | Test | Preconditions | Input | Output | Postconditions
-- | -- | -- | -- | -- | -- | -- | --
3.1.2 | Dashboard | Navigation   Bar | Upload Photo | User is   logged in and on the dashboard page | Click on the   upload photo link | An upload   photo modal will pop up | No change to   the session will be made
-- | -- | -- | -- | -- | -- | -- | --
4.1.1 | Upload Photo Modal | File Filter | Invalid File Type | User is logged in and has opened the upload   photo modal | Click on the 'Choose File' button, and   navigate to and select a file without one of the following extensions: jpg,   jpeg, gif, png; press 'Post' | An error message will popup | No change to the session will be made
-- | -- | -- | -- | -- | -- | -- | --
4.1.2 | Upload Photo   Modal | Post Photo | No   Description | User is   logged in and has opened the upload photo modal | Click on the   'Choose File' button, and navigate to and select a file with one of the   following extensions: jpg, jpeg, gif, png; press 'Post' | A   confirmation message will popup | The new post   will be saved
-- | -- | -- | -- | -- | -- | -- | --
4.1.3 | Upload Photo Modal | Post Photo | Description | User is logged in and has opened the upload   photo modal | Click on the 'Choose File' button, and   navigate to and select a file with one of the following extensions: jpg,   jpeg, gif, png; enter a description in the text field; press 'Post' | A confirmation message will popup     The entered description will be displayed above the photo | The new post will be saved with the   provided description
